package no.capraconsulting.siren.vocabulary

object DublinCore {
    const val ALTERNATIVE = "alternative"
    const val AVAILABLE = "available"
    const val CONTRIBUTOR = "contributor"
    const val CREATED = "created"
    const val CREATOR = "creator"
    const val DESCRIPTION = "description"
    const val EXTENT = "extent"
    const val HAS_VERSION = "hasVersion"
    const val IDENTIFIER = "identifier"
    const val IS_PART_OF = "isPartOf"
    const val IS_REFERENCED_BY = "isReferencedBy"
    const val IS_VERSION_OF = "isVersionOf"
    const val ISSUED = "issued"
    const val MEDIATOR = "mediator"
    const val MODIFIED = "modified"
    const val PROVENANCE = "provenance"
    const val PUBLISHER = "publisher"
    const val REFERENCES = "references"
    const val RELATION = "relation"
    const val REPLACES = "replaces"
    const val SOURCE = "source"
    const val SUBJECT = "subject"
    const val TITLE = "title"
    const val TYPE = "type"
    const val VALID = "valid"
}
